# Krzysztof Nalepa
## Sprawozdanie z ćwiczenia 2

## Algebra liniowa - biblioteki numeryczne 
W środowisku języka Python dostępne są dwie biblioteki numeryczne numpy i scipy. Dokumentacja: https://numpy.org/doc/, https://docs.scipy.org/doc/. Znajdź informacje wyjaśniające różnice między tymi bibliotekami.

### Zadanie 1
Napisz krótki program, który wyświetli informację o wersji biblioteki oraz jej konfiguracji. Zwróć uwagę z jakich bibliotek numerycznych korzystają biblioteki Python'a

In [2]:
import numpy as np
print(f"NumPy version: {np.version.version}")
np.__config__.show()



import scipy as scp
print(f"\nSciPy version: {scp.version.version}")
scp.__config__.show()


NumPy version: 1.18.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

SciPy version: 1.4.1
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 

### Zadanie 2 
Napisz program, który wyświetla wbudowaną pomoc dla funkcji: dodawanie wektorów, 

In [0]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

### Zadanie 3
Napisz programy, które testują wektory danych pod kątem obecności elementów zerowych lub nieskończonych (sprawdź różne warianty takich funkcji). 
Napisz program porównujące wektory i macierze (według wartości elementów).

In [78]:
def zero_elements1(vector):
  print(np.nonzero(vector))
 -inf!!!!!!!
def zero_elements2(vector):
  print(np.where(vector == 0))

def zero_elements3(vector):
  print(np.argwhere(vector))

def inf_elements1(vector):
  print(np.isinf(vector))

def inf_elements2(vector):
  print(np.where(vector == np.inf))

def inf_elements3(vector):
  print(np.argwhere(vector == np.inf))

a = np.array([1,2, np.inf, 0, 0, np.inf])
inf_elements1(a)


[False False  True False False  True]


In [107]:
def compare(matrix_a, matrix_b):
  print(np.equal(matrix_a, matrix_b))

a = np.array([1, 2, 8, 8])
b = np.array([1, 2, 3, 7])
compare(a, b)

print("\n")

x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([[1, 2, 2], [3, 5, 4]])

compare(x, y)


[ True  True False False]


[[ True  True False]
 [ True False False]]


### Zadanie 4 
Napisz program, który wylicza ile danych w bajtach zajmuje wektor lub macierz

In [109]:
def bytes(matrix):
  print(matrix.nbytes)

matrix = np.array([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
bytes(matrix)

72


### Zadanie 5
Napisz kilka programów, które demonstrują jak można w numpy tworzyć wektory i macierze wypełnione różnymi danymi lub mającymi pewną szczególną postać, np. , danymi losowymi, danymi z podanego zakresy, macierze identyczności, ...

In [152]:
def random_matrix(rows, columns):
  return np.random.rand(rows, columns)

def random_vector(size):
  return np.random.rand(size)

def random_matrix_interval(rows, columns, min, max):
  return np.random.randint(size=(rows, columns), low=min, high=max+1)

def random_vector_interval(size, min, max):
  return np.random.randint(size=(size,), low=min, high=max+1)

def identity_matrix(size):
  return np.identity(size)


print(f"random vector: {random_vector(4)}\n")
print(f"random vector with interval: {random_vector_interval(4, 5, 8)}\n")

print(f"random matrix: \n{random_matrix(3, 2)}\n")
print(f"random matrix interval: \n{random_matrix_interval(3, 2, 4, 8)}\n")
print(f"identity matrix: \n{identity_matrix(4)}")


random vector: [0.60992127 0.21860665 0.84126732 0.6368996 ]

random vector with interval: [6 5 6 7]

random matrix: 
[[0.75764203 0.01882742]
 [0.42818047 0.52026552]
 [0.31400326 0.15011636]]

random matrix interval: 
[[6 6]
 [4 4]
 [8 5]]

identity matrix: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Zadania 6
Napisz programy wykonujący podstawowe operacje algebry: dodawanie wektorów, mnożenie wektorów, mnożenia macierzy. Najpierw napisz je w wersji szkolnej, nie zastanawiając się nad jakąkolwiek optymalizacją. Następnie spróbuj zmienić organizację obliczeń tak by uzyskać poprawę wydajności. Na koniec porównaj swoje metody do dedykowanych funkcji z bibliotek NumPy i SciPy. 


In [194]:
import time

def vector_sum(vector1, vector2):
  start = time.time()
  result = []
  i = 0
  for index in range(len(vector1)):
    result += [vector1[index] + vector2[index]]
    i += 1
  end = time.time()
  return result, end - start


def vector_product(vector1, vector2):
  start = time.time()
  result = 0
  i = 0
  for index in range(len(vector1)):
    result += vector1[index] * vector2[index]
    i += 1
  end = time.time()
  return result, end - start


def matrix_product(matrix1, matrix2):
  start = time.time()
  rows1, columns1 = matrix1.shape
  rows2, columns2 = matrix2.shape
  if columns1 != rows2:
    return
  result = np.zeros((rows1,  columns2))
  for i in range(rows1):
    for j in range(columns2):
      for k in range(rows2):
        result[i][j] += matrix1[i][k] * matrix2[k][j]
  end = time.time()
  return result, end - start


def vector_sum_np(vector1, vector2):
  start = time.time()
  result = np.add(vector1, vector2)
  end = time.time()
  return result, end - start


def vector_product_np(vector1, vector2):
  start = time.time()
  result = np.dot(vector1, vector2)
  end = time.time()
  return result, end - start


def matrix_product_np(matrix1, matrix2):
  start = time.time()
  result = np.dot(matrix1, matrix2)
  end = time.time()
  return result, end - start



vector1 = np.array([1,2,3,4,5,6,7])
vector2 = np.array([4,5,6,7,8,9,10])

matrix1 = np.array([[1, 0, 2], [-1, 3, 1]])
matrix2 = np.array([[3, 1], [2, 1], [1, 0]])

print(f"vectors sum: {vector_sum(vector1, vector2)[0]} {vector_sum(vector1, vector2)[1]}")
print(f"vectors sum with numpy: {vector_sum_np(vector1, vector2)[0]} {vector_sum_np(vector1, vector2)[1]}")
print(f"vectors product: {vector_product(vector1, vector2)[0]} {vector_product(vector1, vector2)[1]}")
print(f"vectors product with numpy: {vector_product_np(vector1, vector2)[0]} {vector_product_np(vector1, vector2)[1]}")
print(f"matrix product: \n{matrix_product(matrix1, matrix2)[0]} \n{matrix_product(matrix1, matrix2)[1]}")
print(f"matrix product with numpy: \n{matrix_product_np(matrix1, matrix2)[0]} \n{matrix_product_np(matrix1, matrix2)[1]}")

vectors sum: [5, 7, 9, 11, 13, 15, 17] 4.0531158447265625e-06
vectors sum with numpy: [ 5  7  9 11 13 15 17] 2.86102294921875e-06
vectors product: 224 7.3909759521484375e-06
vectors product with numpy: 224 2.1457672119140625e-06
matrix product: 
[[5. 1.]
 [4. 2.]] 
2.2649765014648438e-05
matrix product with numpy: 
[[5 1]
 [4 2]] 
3.814697265625e-06


Jak widać funkcje biblioteczne są szybsze niż funkcje zaimplementowane przeze mnie. Wynika to prawdopodobnie z tego, że NumPy jest zaimplementowane w C oraz odpowiednio zoptymalizowane.